#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "backrest"
name = "Backrest"
description.en = "Web UI and orchestrator for Restic backup"
description.fr = "Interface Web et orchestrateur pour la sauvegarde Restic"

version = "1.13.0~ynh1"

maintainers = ["DeMiro5001"]

[upstream]
license = "GPL-3.0-only"
admindoc = "https://github.com/garethgeorge/backrest#installation"
userdoc = "https://garethgeorge.github.io/backrest/introduction/getting-started"
code = "https://github.com/garethgeorge/backrest"
fund = "https://buymeacoffee.com/garethgeorge"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/backrest"

    [install.init_main_permission]
    type = "group"
    default = "admins"

[resources]
    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/garethgeorge/backrest/releases/download/v1.13.0/backrest_Linux_x86_64.tar.gz"
    amd64.sha256 = "24102542eceb59054e7714da8cdfd2904c997a8f0bc54f4b2edbcaec38cf337d"
    arm64.url = "https://github.com/garethgeorge/backrest/releases/download/v1.13.0/backrest_Linux_arm64.tar.gz"
    arm64.sha256 = "85a72e949d3bd912eb084423d63cb9eba5f28c65be0239135050284c7b0f65e5"
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*_Linux_x86_64.tar.gz$"
    autoupdate.asset.arm64 = ".*_Linux_arm64.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
